name: documentation

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:


permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          sudo apt-get install -y pandoc
          # pip install sphinx nbsphinx furo pydata-sphinx-theme
          # pip install nbconvert nbformat
          # pip install sphinx-design
          pip install -r docs/requirements.txt
      - name: Sphinx build
        run: |
          cd docs
          make html
          echo '<meta http-equiv="refresh" content="0; url=./html/index.html" />' > build/index.html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/
          force_orphan: true